//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int Id_mensaje { get; set; }
        public int Id_canal { get; set; }
        public int Id_admin { get; set; }
        public int Id_user { get; set; }
        public string Title_mensaje { get; set; }
        public string sub_title_men { get; set; }
        public string cont_men { get; set; }
        public byte[] Date_men { get; set; }
        public Nullable<int> Show_men { get; set; }
        public string Img_men { get; set; }
        public string Status { get; set; }
    
        public virtual Canal Canal { get; set; }
    }
}
