//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Database_asura : DbContext
    {
        public Database_asura()
            : base("name=Database_asura")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administradors { get; set; }
        public virtual DbSet<Canal> Canals { get; set; }
        public virtual DbSet<Mensaje> Mensajes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual ObjectResult<g_user_by_param_id_Result> g_user_by_param_id(Nullable<int> param_fin)
        {
            var param_finParameter = param_fin.HasValue ?
                new ObjectParameter("param_fin", param_fin) :
                new ObjectParameter("param_fin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<g_user_by_param_id_Result>("g_user_by_param_id", param_finParameter);
        }
    
        public virtual int i_user(string nombre, string pass, string repass, string tok, string img, string sts)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var repassParameter = repass != null ?
                new ObjectParameter("Repass", repass) :
                new ObjectParameter("Repass", typeof(string));
    
            var tokParameter = tok != null ?
                new ObjectParameter("Tok", tok) :
                new ObjectParameter("Tok", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("Img", img) :
                new ObjectParameter("Img", typeof(string));
    
            var stsParameter = sts != null ?
                new ObjectParameter("Sts", sts) :
                new ObjectParameter("Sts", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("i_user", nombreParameter, passParameter, repassParameter, tokParameter, imgParameter, stsParameter);
        }
    
        public virtual int up_user(Nullable<int> id, string nombre, string pass, string repass, string tok, string img, string sts)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var repassParameter = repass != null ?
                new ObjectParameter("Repass", repass) :
                new ObjectParameter("Repass", typeof(string));
    
            var tokParameter = tok != null ?
                new ObjectParameter("Tok", tok) :
                new ObjectParameter("Tok", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("Img", img) :
                new ObjectParameter("Img", typeof(string));
    
            var stsParameter = sts != null ?
                new ObjectParameter("Sts", sts) :
                new ObjectParameter("Sts", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_user", idParameter, nombreParameter, passParameter, repassParameter, tokParameter, imgParameter, stsParameter);
        }
    }
}
